services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: app
        image: nazeem-app
        container_name: nazeem-app
        restart: unless-stopped
        entrypoint: sh -c "node ."
        volumes:
            - ./storage:/app/storage
